'View Service PDOK', null, 'http://geodata.nationaalgeoregister.nl/bagviewer/wms?SERVICE=WMS&', null, 0, null, null, 66, 30050);
'Doppler beelden', null, 'http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi?SERVICE=WMS&', null, 0, null, null, 2051, 12069);
'Bodemkaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3ABodemkaart_met_veenkundige_waarden@RD_NEW@png', null, null, 'TMS', null, 2050, 15054);
'Asbestkaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AAsbestlocaties@RD_NEW@png', null, null, 'TMS', null, 2050, 21053);
'KAD', null, 'http://gisopenbaar.overijssel.nl/data/KAD/wms?SERVICE=WMS&', null, 0, null, null, 5050, 122298);
'Definitief voorstel begrenzing +EHS', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/Definitief+voorstel+begrenzing+EHS@RD_NEW@png', null, null, 'TMS', null, 2050, 27050);
'Zwemwater', null, 'http://www.zwemwater.nl/zwr-ogc/services/zwr-wms?', null, 0, null, null, 67, 31053);
'Bedrijventerreinen_O2', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Bedrijventerreinen_O2@RD_NEW@png', null, null, 'TMS', null, 2050, 42052);
'Stedelijk gebied', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_stedelijk_gebied@RD_NEW@png', null, null, 'TMS', null, 2050, 35075);
'Wegencategorieen', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_Wegencategorieen@RD_NEW@png', null, null, 'TMS', null, 2050, 42056);
'Openbaar vervoer netwerk', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_Openbaar_vervoer_netwerk@RD_NEW@png', null, null, 'TMS', null, 2050, 42058);
'Indicatie geschiktheid bodem voor koude_warmte opslag', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_Indicatie_geschiktheid_Koude_warmte_opslag@RD_NEW@png', null, null, 'TMS', null, 2050, 42060);
'Archeologische gebiedenkaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_Archeologische_gebiedenkaart@RD_NEW@png', null, null, 'TMS', null, 2050, 42062);
'Windenergie omgevingsvisie', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_windenergie@RD_NEW@png', null, null, 'TMS', null, 2050, 46053);
'NWB_wegen', null, 'http://geodata.nationaalgeoregister.nl/nwbwegen/wms?SERVICE=WMS&', null, 0, null, null, 66, 54050);
'Subsidiekaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Subsisdiekaart@RD_NEW@png', null, null, 'TMS', null, 2050, 69050);
'Geluidscontouren', null, 'http://mapservices.prorail.nl/ArcGIS/rest/services/Geluidscontouren/MapServer', null, null, null, null, 6050, 76050);
'Leefbarometer', null, 'http://www.leefbaarometer.nl/wms/leefbaarometer/wms?SERVICE=WMS&', null, 0, null, null, 10050, 79194);
'CBS Wijken en Buurten 2012 versie 1 WMS', null, 'http://geodata.nationaalgeoregister.nl/wijkenbuurten2012/wms?SERVICE=WMS&', null, 0, null, null, 12050, 94050);
'test_JDBC', null, 'http://gisopenbaar.overijssel.nl/data/B0/Locaties_projecten/wms?SERVICE=WMS&', null, 0, null, null, 50, 98050);
'Leefbaarheid 2012', 'overzicht', 'http://tiles.arcgis.com/tiles/cH4hp3sAwZPSAeX4/arcgis/rest/services/leefbaarheid_2012/MapServer', 'rigo_maps', null, 'TMS', null, 11050, 103050);
'Energiegebruik_woningen_RD', null, 'http://tiles.arcgis.com/tiles/cH4hp3sAwZPSAeX4/arcgis/rest/services/Energiegebruik_woningen_RD/MapServer', null, null, 'ArcGisRest', null, 11050, 116050);
'PP_ONTW_BEVOLK_TOT14JR_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_ONTW_BEVOLK_TOT14JR_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 136050);
'PP_WONINGWAARDE_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_WONINGWAARDE_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 141051);
'PP_ZIEKENHUIS_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_ZIEKENHUIS_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 141053);
'PP_HUISARTS_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_HUISARTS_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 141055);
'PP_LEVENSLOOPBESTENDIG_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_LEVENSLOOPBESTENDIG_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 141057);
'PP_REL_LEEFBAARHEID_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_REL_LEEFBAARHEID_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 141059);
'PP_EIGENDOMSVERHOUDING_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_EIGENDOMSVERHOUDING_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 141061);
'Asbestscholenkaart', null, 'http://geodata.nationaalgeoregister.nl/asbestscholenkaart/wms?SERVICE=WMS&', null, 0, null, null, 66, 145052);
'Raster', null, 'http://gisopenbaar.overijssel.nl/data/RASTER/wms?SERVICE=WMS&', null, 0, null, null, 50, 141065);
'Shape', null, 'http://gisopenbaar.overijssel.nl/data/SHAPE/wms?SERVICE=WMS&', null, 0, null, null, 50, 121070);
'Lust en leisurelaag', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Lust_en_leisurelaag@RD_NEW@png', null, null, 'TMS', null, 2050, 32050);
'Waterveiligheid omgevingsvisie', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_waterveiligheid@RD_NEW@png', null, null, 'TMS', null, 2050, 40050);
'CWK dijkdoorbraakkolk', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/CWK_dijkdoorbraakkolk@RD_NEW@png', null, null, 'TMS', null, 2050, 45057);
'ondergrond_kleur', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/KLG%3AKLG_ondergrond_kleur@RD_NEW@png', null, null, 'TMS', null, 2050, 55052);
'OpenStreetMap Zonder Gebouwen', null, 'http://www.openbasiskaart.nl/mapcache/tms/1.0.0/osm-nb@rd', null, null, 'TMS', null, 8050, 58052);
'RO-Online: De landelijke voorziening voor digitale ruimtelijke ordeningsplannen', null, 'http://afnemers.ruimtelijkeplannen.nl/afnemers/services?', null, 0, null, null, 7050, 78050);
'Bedrijventerrein_en_veroudering_28C29', null, 'http://tiles.arcgis.com/tiles/cH4hp3sAwZPSAeX4/arcgis/rest/services/Bedrijventerrein_en_veroudering_28C29/MapServer', null, null, 'TMS', null, 11050, 81052);
'PMJP_Versterken_nationale_parken_en_landschappen', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/PMJP_Versterken_nationale_parken_en_landschappen@RD_NEW@png', null, null, 'TMS', null, 2050, 88051);
'Schapenkuddes en Ganzenfourageergebieden', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/PMJP_Schaapskuddes_en_Ganzenfourageergebieden@RD_NEW@png', null, null, 'TMS', null, 2050, 88058);
'Bronhoudersgrenzen', null, 'http://geoweb.hengelo.nl/ArcGIS/rest/services/extern/Bronhoudersgrenzen/MapServer', null, null, null, null, 13050, 110050);
'RAGO_group', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_RAGO_group@RD_NEW@png', null, null, 'TMS', null, 2050, 112061);
'PP_GEBTYP_SOC_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_GEBTYP_SOC_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 137062);
'Overstromingsdiepten', null, 'http://flod-geoserver1.lizard.net:80/geoserver/ror/wms?SERVICE=WMS&', null, 0, null, null, 67, 122211);
'PP_GEBTYP_FYS_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_GEBTYP_FYS_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 137064);
'ror t100_waterdiepte_o', null, 'http://flod-geoserver1.lizard.net/geoserver/gwc/service/tms/1.0.0/ror%3At100_waterdiepte_o@EPSG%3A28992@png', null, null, 'TMS', null, 67, 122284);
'ror t100_waterdiepte_b', null, 'http://flod-geoserver1.lizard.net/geoserver/gwc/service/tms/1.0.0/ror%3At100_waterdiepte_b@EPSG%3A28992@png', null, null, 'TMS', null, 67, 122294);
'Referentie', null, 'http://gisopenbaar.overijssel.nl/data/B0/wms?SERVICE=WMS&', null, 0, null, null, 50, 96050);
'IPOluchtfoto', null, 'http://luchtfoto.services.gbo-provincies.nl/tilecache/tilecache.aspx/1.0.0/IPOlufo/', null, null, 'TMS', null, 67, 68);
'Actueel Hoogtebestand Nederland', null, 'http://ahn.services.gbo-provincies.nl/mapserv.cgi?map=ahn1.map&reaspect=false&SERVICE=wms&', null, 0, null, null, 67, 70);
'Openbaar bestuur', null, 'http://gisopenbaar.overijssel.nl/data/B1/wms?SERVICE=WMS&', null, 0, null, null, 50, 132089);
'Buienradar_Buienradar', null, 'http://arcgis93.esri.nl/arcgis/services/Buienradar/Buienradar/MapServer/WMSServer', null, 0, null, null, 2051, 12063);
'Ecologische hoofdstructuur', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AEcologische_hoofdstructuur@RD_NEW@png', null, null, 'TMS', null, 2050, 18195);
'Habitattypen_habitatrichtijn', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AHabitattypen_habitatrichtijn@RD_NEW@png', null, null, 'TMS', null, 2050, 20050);
'Definitief voorstel zeer kwetsbare gebieden', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3ADefinitief_voorstel_zeer_kwetsbare_gebieden@RD_NEW@png', null, null, 'TMS', null, 2050, 27058);
'Agrarisch cultuurlandschap', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Agrarisch_cultuurlandschap@RD_NEW@png', null, null, 'TMS', null, 2050, 34071);
'Overig water', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_overig@RD_NEW@png', null, null, 'TMS', null, 2050, 37050);
'Waterveiligheid verordening', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_verord_waterveiligheid@RD_NEW@png', null, null, 'TMS', null, 2050, 38059);
'Verblijfsrecreatie en routestructuren omgevingsvisie', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_verblijfsrecreatieenroutestructuren@RD_NEW@png', null, null, 'TMS', null, 2050, 39050);
'Weidevogel en ganzengebieden', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AAVO_weidevogel_en_ganzengebieden@RD_NEW@png', null, null, 'TMS', null, 2050, 39065);
'Nationale landschappen en Parken', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_Nationale_landschappen_en+parken@RD_NEW@png', null, null, 'TMS', null, 2050, 39067);
'Drinkwaterwinningen', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_drinkwaterwinningen@RD_NEW@png', null, null, 'TMS', null, 2050, 39069);
'Archeologische verwachtingskaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B7%3AArcheologische_verwachtingskaart@RD_NEW@png', null, null, 'TMS', null, 2050, 40073);
'Zandwin en zoutlocaties', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Zandwin_en_zoutlocaties@RD_NEW@png', null, null, 'TMS', null, 2050, 42050);
'Ontwikkelingsperspectieven visie', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Ontwikkelingsperspectieven_visie@RD_NEW@png', null, null, 'TMS', null, 2050, 43050);
'EHS_ONW', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_EHS@RD_NEW@png', null, null, 'TMS', null, 2050, 45059);
'Faunaknelpunten omgevingsvisie', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/Faunaknelpunten_omgevingsvisie@RD_NEW@png', null, null, 'TMS', null, 2050, 46055);
'Luchthavenregeling', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B6%3ALuchthavenregeling_samengevoegd@RD_NEW@png', null, null, 'TMS', null, 2050, 87050);
'bevolking_75_jaar_ouder_28B29', null, 'http://tiles.arcgis.com/tiles/cH4hp3sAwZPSAeX4/arcgis/rest/services/bevolking_75_jaar_ouder_28B29/MapServer', 'maps_rigo', null, 'TMS', null, 11050, 81050);
'cascokaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3Acascokaart@RD_NEW@png', null, null, 'TMS', null, 2050, 102052);
'Risicokaart', null, 'http://servicespub.risicokaart.nl/rk_services_pub/services/WMS-risicokaart?', null, 0, null, null, 67, 122050);
'Web Map Service risicokaart_pub_nl', null, 'http://nederlandwms.risicokaart.nl:80/wmsconnector/com.esri.wms.Esrimap/risicokaart_pub_nl?', null, 0, null, null, 67, 121062);
'Inspire view Service Hydrografie en Administratieve eenheden', null, 'http://maps.waterschapservices.nl:80/inspire/wms?SERVICE=WMS&', null, 0, null, null, 14053, 115080);
'ror t10_waterdiepte_o', null, 'http://flod-geoserver1.lizard.net/geoserver/gwc/service/tms/1.0.0/ror%3At10_waterdiepte_o@EPSG%3A28992@png', null, null, 'TMS', null, 67, 122278);
'PP_BEVOLK_TOT14JR_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_BEVOLK_TOT14JR_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 137056);
'AHN2', null, 'http://geodata.nationaalgeoregister.nl/tiles/service/wmts/ahn2?VERSION=1.0.0&request=GetCapabilities', null, null, 'TMS', null, 66, 145050);
'Top10NL', null, 'http://geodata.nationaalgeoregister.nl/tms/1.0.0/top10nl@EPSG:28992@png8', null, null, 'TMS', null, 66, 82);
'Adressen WMS', null, 'http://geodata.nationaalgeoregister.nl/inspireadressen/wms?SERVICE=WMS&', null, 0, null, null, 66, 84);
'Geomorfologische kaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AGeomorfologische_kaart@RD_NEW@png', null, null, 'TMS', null, 2050, 12055);
'Beheertypenkaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Beheertypenkaart_groep@RD_NEW@png', null, null, 'TMS', null, 2050, 12057);
'Hemelhelderheid nachtelijke uren', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AHemelhelderheid_nachtelijke_uren@RD_NEW@png', null, null, 'TMS', null, 2050, 26054);
'Ontwerp_begrenzing EHS en zone ondernemen met natuur en water', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AOntwerp_begrenzing_EHS_en_zone_ondernemen_met_natuur_en_water@RD_NEW@png', null, null, 'TMS', null, 2050, 26056);
'Ger_carmon', null, 'http://195.190.28.198/cgi-bin/mapserv.exe?map=overijssel.map', null, 0, null, null, 3050, 20073);
'Geluidscontouren spoorwegen', null, 'http://mapservices.prorail.nl/ArcGIS/services/Geluidscontouren/MapServer/WMSServer', null, 0, null, null, 6050, 31050);
'Waterberging', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Waterberging@RD_NEW@png', null, null, 'TMS', null, 2050, 37052);
'Ontwikkelingsperspectieven verordening', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Ontwikkelingsperspectieven_verordening@RD_NEW@png', null, null, 'TMS', null, 2050, 37064);
'Externe veiligheid verordening', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_verord_externe_veiligheid@RD_NEW@png', null, null, 'TMS', null, 2050, 38065);
'Hoofdinfrastructuur O2', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_omg_hoofdinfrastructuur@RD_NEW@png', null, null, 'TMS', null, 2050, 42054);
'bp_svbp_all', null, 'http://afnemers.ruimtelijkeplannen.nl/geowebcache/service/tms/1.0.0/bp_svbp_all@urn:ogc:def:wkss:OGC:1.0:NLDEPSG28992Scale512px@png', null, null, 'TMS', null, 7050, 45080);
'KLG_ondergrond_kleur_sept2013', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/KLG%3AKLG_ondergrond_kleur@RD_NEW@png', null, null, 'TMS', null, 64, 57050);
'openstreetmap', null, 'http://www.openbasiskaart.nl/mapcache/tms/1.0.0/osm@rd', null, null, 'TMS', null, 8050, 58050);
'IMNA_Beheertypenkaart', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/SHAPE%3AIMNA_Beheertypenkaart_a@RD_NEW@png', null, null, 'TMS', null, 2050, 69052);
'digitaaltopografischbestand', null, 'http://geodata.nationaalgeoregister.nl/digitaaltopografischbestand/wms?SERVICE=WMS&', null, 0, null, null, 14050, 115052);
'Horus Web Map Service', null, 'http://viewer.horus.nu:80/geoserver/wms?SERVICE=WMS&', null, 0, null, null, 15050, 133050);
'ror t1000_waterdiepte_b', null, 'http://flod-geoserver1.lizard.net/geoserver/gwc/service/tms/1.0.0/ror%3At1000_waterdiepte_b@EPSG%3A28992@png', null, null, 'TMS', null, 67, 122296);
'test_andre', null, 'http://gisopenbaar.overijssel.nl/data/B2/wms?SERVICE=WMS&', null, 0, null, null, 50, 130055);
'PP_ENERGIEGEBRUIK_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_ENERGIEGEBRUIK_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 140099);
'PP_BEVOLK_75PLUS_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_BEVOLK_75PLUS_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 137058);
'ASBESTINVENTARISATIE_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3AASBESTINVENTARISATIE_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 144051);
'H2O', null, 'http://gisopenbaar.overijssel.nl/data/H2O/wms?SERVICE=WMS&', null, 0, null, null, 50, 140097);
'ondergrond_overijssel_kleur_febr2013', null, 'http://gisopenbaar.overijssel.nl/ArcGIS/rest/services/Ondergronden/ondergrond_overijssel_kleur_febr2013/MapServer', null, null, 'ArcGisRest', null, 64, 50);
'Wegenkaart', null, 'http://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0/brtachtergrondkaart@EPSG:28992@png8/', null, null, 'TMS', null, 66, 52);
'Natuur en milieu', null, 'http://gisopenbaar.overijssel.nl/data/B4/wms?SERVICE=WMS&', null, 0, null, null, 50, 144054);
'Kadastrale kaart (BRK)', null, 'http://geodata.nationaalgeoregister.nl/kadastralekaart/wms?SERVICE=WMS&', null, 0, null, null, 66, 26050);
'Verkeer en vervoer', null, 'http://gisopenbaar.overijssel.nl/data/B2/wms?SERVICE=WMS&', null, 0, null, null, 50, 128094);
'Water', null, 'http://gisopenbaar.overijssel.nl/data/B3/wms?SERVICE=WMS&', null, 0, null, null, 50, 125053);
'Toerisme en recreatie', null, 'http://gisopenbaar.overijssel.nl/data/B5/wms?SERVICE=WMS&', null, 0, null, null, 50, 72050);
'Economie en landbouw', null, 'http://gisopenbaar.overijssel.nl/data/B6/wms?SERVICE=WMS&', null, 0, null, null, 50, 135050);
'Zorg en cultuur', null, 'http://gisopenbaar.overijssel.nl/data/B7/wms?SERVICE=WMS&', null, 0, null, null, 50, 93057);
'Ruimtelijke ontwikkeling en inrichting', null, 'http://gisopenbaar.overijssel.nl/data/B8/wms?SERVICE=WMS&', null, 0, null, null, 50, 144055);
'Openbare orde en veiligheid', null, 'http://gisopenbaar.overijssel.nl:80/data/B9/wms?SERVICE=WMS&', null, 0, null, null, 50, 33099);
'Overlay wegen', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/overlay_wegen@RD_NEW@png', null, null, 'TMS', null, 2050, 86059);
'Wijkindeling', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3AWijkindeling@RD_NEW@png', null, null, 'TMS', null, 2050, 13058);
'Grondwatertrappen', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B4%3ABodemkaart_met_grondwatertrappen@RD_NEW@png', null, null, 'TMS', null, 2050, 15052);
'Natuurlijke laag', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_natuurlijke_laag@RD_NEW@png', null, null, 'TMS', null, 2050, 32054);
'Continue en herkenbaar watersysteem', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B3%3AAVO_Continue_en_herkenbaar_watersysteem@RD_NEW@png', null, null, 'TMS', null, 2050, 36052);
'Waterveiligheid', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Waterveiligheid@RD_NEW@png', null, null, 'TMS', null, 2050, 36054);
'Grondwater', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B3%3AAVO_grondwater@RD_NEW@png', null, null, 'TMS', null, 2050, 37054);
'Recreatie verordening', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_verord_recreatie@RD_NEW@png', null, null, 'TMS', null, 2050, 38067);
'Waterlopen en waterberging', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_Waterlopen_en_Waterberging@RD_NEW@png', null, null, 'TMS', null, 2050, 41068);
'B2 - test', null, 'http://gisopenbaar.overijssel.nl/data/B2_test/wms?SERVICE=WMS&', null, 0, null, null, 50, 121059);
'Sociale vitaliteit (PMJP)', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/PMJP_Sociale_vitaliteit@RD_NEW@png', null, null, 'TMS', null, 2050, 89050);
'PMJP Ruimte voor water', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/PMJP_Ruimte_voor_water@RD_NEW@png', null, null, 'TMS', null, 2050, 91090);
'Vierkanten 500m x 500m WMS', null, 'http://geodata.nationaalgeoregister.nl/cbsvierkanten500m/wms?SERVICE=WMS&', null, 0, null, null, 12050, 94054);
'Vierkanten 100m x 100m WMS', null, 'http://geodata.nationaalgeoregister.nl/cbsvierkanten100m/wms?SERVICE=WMS&', null, 0, null, null, 12050, 94133);
'RAGO_group1', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/AVO_RAGO_group@RD_NEW@png', null, null, 'TMS', null, 2050, 115050);
'INSPIRE View service voor AgriculturalAndAquacultureFacilities van de gezamenlijke provincies', null, 'http://services.inspire-provincies.nl/AgriculturalAndAquacultureFacilities/services/view_AF?', null, 0, null, null, 15051, 133075);
'Signaleringskaart', null, 'http://nederlandprofsig.deegree.risicokaart.nl/signaleringskaart_wms_wfs/services?', null, 0, null, null, 67, 122152);
'ror t1000_waterdiepte_o', null, 'http://flod-geoserver1.lizard.net/geoserver/gwc/service/tms/1.0.0/ror%3At1000_waterdiepte_o@EPSG%3A28992@png', null, null, 'TMS', null, 67, 122286);
'PP_ONTW_BEVOLK_75PLUS_POLYGON', null, 'http://gisopenbaar.overijssel.nl/data/gwc/service/tms/1.0.0/B8%3APP_ONTW_BEVOLK_75PLUS_POLYGON@RD_NEW@png', null, null, 'TMS', null, 2050, 137060);
